[project]
name = "functionfinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["typer", "rich"]

[project.optional-dependencies]
dev = ["pytest", "typer"]